# Generated by Django 5.0.7 on 2024-07-30 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('code_review', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RepositoryAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('repo_name', models.CharField(max_length=255, unique=True)),
                ('url', models.CharField(max_length=1024)),
                ('context', models.TextField()),
                ('feedback', models.TextField()),
                ('score', models.IntegerField()),
                ('updated_file_structure', models.JSONField()),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Repository',
        ),
    ]
