# Generated by Django 5.0.7 on 2024-07-31 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('code_review', '0002_repositoryanalysis_delete_repository'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repositoryanalysis',
            name='context',
            field=models.TextField(null=True),
        ),
    ]
