# Generated by Django 5.0.7 on 2024-07-31 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('code_review', '0003_alter_repositoryanalysis_context'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repositoryanalysis',
            name='context',
            field=models.TextField(default='', null=True),
        ),
    ]
