# Generated by Django 5.0.7 on 2024-07-31 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('code_review', '0005_fileanalysis'),
    ]

    operations = [
        migrations.RenameField(
            model_name='repositoryanalysis',
            old_name='last_updated',
            new_name='updated_at',
        ),
        migrations.AddField(
            model_name='repositoryanalysis',
            name='last_commit_hash',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='repositoryanalysis',
            name='context',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='repositoryanalysis',
            name='score',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='repositoryanalysis',
            name='url',
            field=models.URLField(),
        ),
    ]
