# Generated by Django 5.0.7 on 2024-07-31 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "code_review",
            "0006_rename_last_updated_repositoryanalysis_updated_at_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="repositoryanalysis",
            name="url",
            field=models.CharField(max_length=1000),
        ),
    ]
